apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: 'app-of-apps'
spec:
  destination:
    name: 'in-cluster'
    namespace: 'argocd'
  source:
    path: 'K8/manifests/apps'
    repoURL: 'https://github.com/williamdunstanmorris/IaC'
    targetRevision: HEAD
  project: 'default'
