apiVersion: apps/v1
kind: Deployment
metadata:
  name: release-name-bluejay
  labels:
    helm.sh/chart: bluejay-0.1.0
    app.kubernetes.io/name: bluejay
    app.kubernetes.io/instance: release-name
    app.kubernetes.io/version: "1.0.0"
    app.kubernetes.io/managed-by: Helm
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: bluejay
      app.kubernetes.io/instance: release-name
  template:
    metadata:
      labels:
        helm.sh/chart: bluejay-0.1.0
        app.kubernetes.io/name: bluejay
        app.kubernetes.io/instance: release-name
        app.kubernetes.io/version: "1.0.0"
        app.kubernetes.io/managed-by: Helm
    spec:
      serviceAccountName: bluejay
      containers:
        - name: bluejay
          image: "europe-west1-docker.pkg.dev/YOUR_PROJECT/main/bluejay:1.0.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi

