apiVersion: apps/v1
kind: Deployment
metadata:
  name: bluejay-argocd
  labels:
    app: bluejay-argocd
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bluejay-argocd
  template:
    metadata:
      labels:
        app: bluejay-argocd
    spec:
      containers:
        - name: bluejay
          image: europe-west3-docker.pkg.dev/project-2b40a90c-1a89-477e-894/main/bluejay
          ports:
            - containerPort: 8080