kind: HTTPRoute
apiVersion: gateway.networking.k8s.io/v1
metadata:
  name: store-external
spec:
  parentRefs:
    # Bind the route to the 'external-http' Gateway.
    - kind: Gateway
      name: external-regional-http
  hostnames:
    - "bluejay.subcloudlabs.com"
  rules:
    # Default rule for store.example.com that sends traffic to the store-v1 service.
    - backendRefs:
        - name: ext-store-v1
          port: 8080
