apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ .Values.gateway.name }}
spec:
  gatewayClassName: {{ .Values.gateway.gatewayClassName }}
  listeners:
    {{- range .Values.gateway.listeners }}
    - name: {{ .name }}
      protocol: {{ .protocol }}
      port: {{ .port }}
      {{- if .tls }}
      tls:
        mode: {{ .tls.mode }}
        certificateRefs:
          {{- range .tls.certificateRefs }}
          - name: {{ . }}
          {{- end }}
      {{- end }}
    {{- end }}
  {{- if .Values.gateway.addresses }}
  addresses:
    {{- toYaml .Values.gateway.addresses | nindent 4 }}
  {{- end }}